name: "Testing"

on:
  push:
    branches:
      - main

jobs:
  test_the_action:
    #if: "contains(github.event.head_commit.message, 'backend')"
    name: Test the action
    runs-on: ubuntu-22.04
    env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
    steps:
      - name: Log
        shell: bash
        run: echo "$webhook_url"
      - name: Webhook
        uses: distributhor/workflow-webhook@v3.0.5
