name: "Testing"

on:
  push:
    branches:
      - main

jobs:
  test_the_action:
    if: "contains(github.event.head_commit.message, 'backend')"
    name: Test the action
    runs-on: ubuntu-18.04
    steps:
      - name: Webhook
        uses: distributhor/workflow-webhook@v3.0.5
        with:
            url: "https://webhook.site/a3c71d18-3c40-43ce-a952-529e06123799"
